name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente
  workflow_dispatch:  # Permite ejecución manual

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: lauracs6
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push the animation to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add resources/img/github-contribution-grid-snake.svg || exit 0
          git commit -m "Update Snake animation" || exit 0
          git push


